language: generic
dist: trusty

services: 
  - docker

before_install:
  # make docker run on a ramdisk
  - sudo rm /etc/default/docker
  - mkdir /tmp/docker
  - free -m
  - df -h
  # add swap space so that we can exceed the ram with our ramdisk
  - sudo fallocate -l 16G /tmp/swapfile
  - sudo chmod 600 /tmp/swapfile
  - sudo mkswap /tmp/swapfile
  - sudo swapon /tmp/swapfile
  - sudo swapon -s
  - free -m
  - sudo sysctl vm.swappiness=10
  - sudo sysctl vm.vfs_cache_pressure=50
  # mount the ramdisk
  - sudo mount -t tmpfs -o size=20G tmpfs /tmp/docker
  - echo "DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /tmp/docker\"" | sudo tee /etc/default/docker > /dev/null
  - sudo restart docker
  # install build requirements
  - sudo apt-get install dc
  - sudo pip install docker-release
  - docker-release --version
  - free -m
  # prime the cache by fetching the latest release of all images
  # - ls teradatalabs/ | awk '{print "teradatalabs/" $0 }' | xargs -L1 time docker pull || true

install: make
